version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: task-management-api-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: task-management-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres